site_name: 🧪 Laboratório de Estudos .NET
site_url: https://heviane.github.io/dotnet-lab/
repo_url: https://github.com/heviane/dotnet-lab
repo_name: heviane/dotnet-lab
edit_uri: edit/main/docs/ # Ajuste para apontar para a pasta de documentação

theme:
  name: material
  language: pt
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    # Palette toggle for dark vs light mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

# É uma boa prática definir explicitamente o diretório dos documentos.
docs_dir: docs

nav:
  - "Início": index.md
  - "Guias de Projetos":
    - "Requisitos de Ambiente": guides/requirements-guide.md
    - "Guia de Comandos .NET CLI": guides/dotnet-cli-guide.md
    - "Guia de Versionamento": guides/versioning-guide.md
  - "Guias de Estudos":
    - "Trilha de Aprendizagem": courses/index.md
  - ".NET":
    - "Arquivo de Solução (.sln)": courses/dotnet/solution-file-explained.md
  - "C# (POO)":
    - "Classes": courses/csharp/oop/classes.md
    - "Objetos": courses/csharp/oop/objects.md
    - "Herança": courses/csharp/oop/inheritance.md
    - "Polimorfismo": courses/csharp/oop/polymorphism.md
    - "Encapsulamento": courses/csharp/oop/encapsulation.md
    - "Abstração": courses/csharp/oop/abstraction.md
    - "Interfaces": courses/csharp/oop/interfaces.md
    - "Classes Abstratas": courses/csharp/oop/abstract-classes.md
    - "Métodos e Funções": courses/csharp/oop/methods-and-functions.md
  - "C# Introdução":
    - "Tipos de Dados": courses/csharp/fundamental/datatype.md
    - "Variáveis": courses/csharp/fundamental/variable.md
    - "Expressões": courses/csharp/fundamental/expressions.md
    - "Estruturas de Controle": courses/csharp/fundamental/control-structures.md
    - "Escopo de Variáveis": courses/csharp/fundamental/scope-of-variables.md
    - "Manipulação de Strings": courses/csharp/fundamental/string-manipulation.md
    - "Manipulação de Arquivos": courses/csharp/fundamental/file-handling.md
