site_name: 🧪 Laboratório de Estudos .NET
site_url: https://heviane.github.io/dotnet-lab/
repo_url: https://github.com/heviane/dotnet-lab
repo_name: heviane/dotnet-lab
edit_uri: edit/main/docs/ # Ajuste para apontar para a pasta de documentação

theme:
  name: material
  language: pt
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    # Palette toggle for dark vs light mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

# É uma boa prática definir explicitamente o diretório dos documentos.
docs_dir: docs

nav:
  - "Início": index.md
  - "Guias do Projeto":
      - "Trilha de Aprendizagem .NET": dotnet-learning-plan.md
      - "Requisitos": requirements-guide.md
      - "Guia de Versionamento": versioning-guide.md
      - "Arquivo de Solução (.sln)": solution-file-explained.md
      - "Guia .NET CLI": dotnet-cli-guide.md
      - "Cursos e Anotações":
          - "Conceitos Gerais": courses/conceitos-gerais-programacao.md
          - "C#":
              - "Fundamentos": courses/charp/fundamentos/README.md

